variable "workspace" {}
variable "domain_name" {}
variable "aws_current_user_id" {}
variable "prefix" {}
variable "certificate_arn" {}
variable "api_path" {}
variable "region_name" {}
variable "aws_account_id" {}
variable "github_action_role_id" {}
